import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        { /* eslint-disable-next-line @next/next/no-sync-scripts */ }
        <script src="https://polyfill.io/v3/polyfill.min.js?features=globalThis"></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
